### ISSUE TITLE
Add a warning to the docs that o-fonts doesn't use o-assets

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-assets#21]

**Comment by triblondon** [comment]
This probably ought to be a code comment where the path is defined as well. My understanding of the issue is:

* Can't store the font files in o-fonts due to licensing issues
* Therefore they are in a private stash repo that is not a dependency of o-fonts (if it were a dependency then Travis CI would not be able to build o-fonts for testing)
* We can't use o-assets to resolve a path to a file that is not in a declared dependency, because it will output a path that may not exist.

That said, this all seems really ugly, and introduces loads of problems that o-assets is designed to solve. I wonder if we really can't have o-fonts-assets as a dependency.  Maybe there's a way around that which still allows us to test on Travis?

**Comment by onishiweb** [comment]
Any update on this issue?

**Comment by wheresrhys** [comment]
o-icons is now also moving to use image service to deliver assets. Is using origami services to deliver assets the new normal, and if so
a) should all modules default to use origami services
b) do we even need o-assets any more

**Comment by AlbertoElias** [comment]
o-icons supports using o-assets. I think o-assets is still being used, and I think it makes sense that modules might have their own assets and products should choose how to serve them.
